a = 10 
b = 20

try{
    console.log("hello world hi")
    console.log(a+b)
}
catch(err){
    console.log(err.message);
    
}
finally{
    console.log("this is finally block")
}
